
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - CORS_ORIGIN_WHITELIST=http://localhost:3000
      - ALLOWED_HOSTS=localhost backend
      - SECRET_KEY=your-django-secret-key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - backend_static:/staticfiles
      - backend_data:/db_data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws/chat
    restart: unless-stopped

volumes:
  backend_static:
  backend_data:
