GET http://127.0.0.1:8000/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MDQ0NTQyLCJpYXQiOjE3MTYwNDM2NTgsImp0aSI6IjdjMDkwMDM0NWM2ZjQ4YTc4ZjE5ZDJjMGZlZjJmODM3IiwidXNlcl9pZCI6ImQ0ZTc2MWIyLTliZGUtNGI1OS05ZjViLTJlYWQzOWY0NWIzOSJ9.2aUjSF2LtT2KMVXqDcgPdkbqvM9YvZBQyvdKQ4wVOdY

