GET http://127.0.0.1:8000/api/users/mzeggfaf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzExMjMxMjgxLCJpYXQiOjE3MTEyMzA5ODEsImp0aSI6IjJkODEzODM1OWJjNTRiOTdhYjFhZTVkYWQyYWE3NTUxIiwidXNlcl9pZCI6MzZ9.4-1Z0QzYQqaZyBgbo_AsdzoTF-3s8xp4ehrWAdPQe7E

# username: "mzeggaf"
# access:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzExMjMxMjgxLCJpYXQiOjE3MTEyMzA5ODEsImp0aSI6IjJkODEzODM1OWJjNTRiOTdhYjFhZTVkYWQyYWE3NTUxIiwidXNlcl9pZCI6MzZ9.4-1Z0QzYQqaZyBgbo_AsdzoTF-3s8xp4ehrWAdPQe7E"