### Backend Development Dockerfile ###

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/

# Don't collect static files in development
# RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Make entrypoint executable
COPY entrypoint-dev.sh /app/
RUN chmod +x /app/entrypoint-dev.sh

# Use development entrypoint script (with Daphne)
ENTRYPOINT ["/app/entrypoint-dev.sh"]
