# Generated by Django 4.2.11 on 2024-03-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_todo_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='completed',
        ),
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
