# Generated by Django 4.2.11 on 2024-03-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chat_completed_chat_topic_alter_chat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
