# Generated by Django 4.2.11 on 2024-03-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
