# Generated by Django 5.1 on 2024-08-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
