# Generated by Django 4.2.11 on 2024-03-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
