# Generated by Django 5.1 on 2024-08-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_delete_chatbot_appuser_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='ai',
            new_name='is_ai',
        ),
    ]
