# Generated by Django 5.1 on 2024-08-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_rename_ai_appuser_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
