# Generated by Django 5.1 on 2024-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_appuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
