# Generated by Django 5.1 on 2024-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_appuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
